name: "Convert to python version flavour"

on:
  workflow_call:
    inputs:
        VERSIONTAG:
            description: "The Version Tag ie. 1.13.2~rc6"
            required: true
            type: string
    outputs:
        pyVersion:
            description: "The python converted version"
            value: ${{ jobs.pyVersion.outputs.pyVersion }}
        debVersion:
            description: "The debian converted version"
            value: ${{ jobs.pyVersion.outputs.debVersion }}

jobs:
    pyVersion:
        runs-on: ubuntu-latest
        outputs:
            pyVersion: ${{ steps.conversion.outputs.pyVersion }}
            debVersion: ${{ steps.conversion.outputs.debVersion }}
        steps:
            - name: Convert to python version flavour
              id: conversion
              run: |
                pyVersion=$(echo ${{ inputs.VERSIONTAG }} | sed 's~v~~g')
                if [[ ${pyVersion} == *"-"* ]]; then
                  pyVersion=$(echo ${pyVersion} | sed 's~-~.~g')
                fi
                echo "pyVersion=${pyVersion}" >> $GITHUB_OUTPUT
                echo "debVersion=$(echo ${pyVersion} | sed -E 's/^([^\.]*\.[^\.]*\.[^\.]*)\.(.*)$/\1~\2/')" >> $GITHUB_OUTPUT